name: Auto Renew Sillydev Server

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  renew-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright and dependencies
        run: |
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run Server Renewal Script
        env:
          SILLYDEV_COOKIE: ${{ secrets.SILLYDEV_COOKIE }}
          SILLYDEV_EMAIL: ${{ secrets.SILLYDEV_EMAIL }}
          SILLYDEV_PASSWORD: ${{ secrets.SILLYDEV_PASSWORD }}
        run: python -u main.py

      # 【【【 核心修改点: 总是上传产物 】】】
      # 将 if: failure() 改为 if: always() 以便在调试阶段总是能看到截图
      - name: Upload debug artifacts
        if: always() # 无论成功或失败，都上传产物
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-and-logs
          path: "*.png" # 上传所有以 .png 结尾的文件
